name: Build Fabric Mod

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - run: chmod +x gradlew || true
      - run: ./gradlew build

      - uses: actions/upload-artifact@v4
        with:
          name: mod-jar
          path: build/libs/*.jar
